/**
 * Bible Reading Plans Data
 * Daily reading schedules for various Bible reading plans
 */

export interface DailyReading {
  day: number;
  readings: {
    book: string;
    chapters: string; // e.g., "1-3" or "1"
  }[];
  title?: string; // Optional title for the day's theme
}

export interface ReadingPlanSchedule {
  planId: string;
  schedule: DailyReading[];
}

/**
 * Bible in a Year - 365 Day Reading Plan
 * Covers Old Testament, New Testament, Psalms & Proverbs
 */
export const bibleInYearSchedule: DailyReading[] = [
  // January (Days 1-31)
  { day: 1, readings: [{ book: "Genesis", chapters: "1-2" }, { book: "Matthew", chapters: "1" }, { book: "Psalms", chapters: "1" }] },
  { day: 2, readings: [{ book: "Genesis", chapters: "3-4" }, { book: "Matthew", chapters: "2" }, { book: "Psalms", chapters: "2" }] },
  { day: 3, readings: [{ book: "Genesis", chapters: "5-7" }, { book: "Matthew", chapters: "3" }, { book: "Psalms", chapters: "3" }] },
  { day: 4, readings: [{ book: "Genesis", chapters: "8-10" }, { book: "Matthew", chapters: "4" }, { book: "Psalms", chapters: "4" }] },
  { day: 5, readings: [{ book: "Genesis", chapters: "11-13" }, { book: "Matthew", chapters: "5" }, { book: "Psalms", chapters: "5" }] },
  { day: 6, readings: [{ book: "Genesis", chapters: "14-16" }, { book: "Matthew", chapters: "6" }, { book: "Psalms", chapters: "6" }] },
  { day: 7, readings: [{ book: "Genesis", chapters: "17-18" }, { book: "Matthew", chapters: "7" }, { book: "Psalms", chapters: "7" }] },
  { day: 8, readings: [{ book: "Genesis", chapters: "19-20" }, { book: "Matthew", chapters: "8" }, { book: "Psalms", chapters: "8" }] },
  { day: 9, readings: [{ book: "Genesis", chapters: "21-23" }, { book: "Matthew", chapters: "9" }, { book: "Psalms", chapters: "9" }] },
  { day: 10, readings: [{ book: "Genesis", chapters: "24" }, { book: "Matthew", chapters: "10" }, { book: "Psalms", chapters: "10" }] },
  { day: 11, readings: [{ book: "Genesis", chapters: "25-26" }, { book: "Matthew", chapters: "11" }, { book: "Psalms", chapters: "11" }] },
  { day: 12, readings: [{ book: "Genesis", chapters: "27-28" }, { book: "Matthew", chapters: "12" }, { book: "Psalms", chapters: "12" }] },
  { day: 13, readings: [{ book: "Genesis", chapters: "29-30" }, { book: "Matthew", chapters: "13" }, { book: "Psalms", chapters: "13" }] },
  { day: 14, readings: [{ book: "Genesis", chapters: "31-32" }, { book: "Matthew", chapters: "14" }, { book: "Psalms", chapters: "14" }] },
  { day: 15, readings: [{ book: "Genesis", chapters: "33-35" }, { book: "Matthew", chapters: "15" }, { book: "Psalms", chapters: "15" }] },
  { day: 16, readings: [{ book: "Genesis", chapters: "36-37" }, { book: "Matthew", chapters: "16" }, { book: "Psalms", chapters: "16" }] },
  { day: 17, readings: [{ book: "Genesis", chapters: "38-40" }, { book: "Matthew", chapters: "17" }, { book: "Psalms", chapters: "17" }] },
  { day: 18, readings: [{ book: "Genesis", chapters: "41" }, { book: "Matthew", chapters: "18" }, { book: "Psalms", chapters: "18" }] },
  { day: 19, readings: [{ book: "Genesis", chapters: "42-43" }, { book: "Matthew", chapters: "19" }, { book: "Psalms", chapters: "19" }] },
  { day: 20, readings: [{ book: "Genesis", chapters: "44-45" }, { book: "Matthew", chapters: "20" }, { book: "Psalms", chapters: "20" }] },
  { day: 21, readings: [{ book: "Genesis", chapters: "46-47" }, { book: "Matthew", chapters: "21" }, { book: "Psalms", chapters: "21" }] },
  { day: 22, readings: [{ book: "Genesis", chapters: "48-50" }, { book: "Matthew", chapters: "22" }, { book: "Psalms", chapters: "22" }] },
  { day: 23, readings: [{ book: "Exodus", chapters: "1-3" }, { book: "Matthew", chapters: "23" }, { book: "Psalms", chapters: "23" }] },
  { day: 24, readings: [{ book: "Exodus", chapters: "4-6" }, { book: "Matthew", chapters: "24" }, { book: "Psalms", chapters: "24" }] },
  { day: 25, readings: [{ book: "Exodus", chapters: "7-8" }, { book: "Matthew", chapters: "25" }, { book: "Psalms", chapters: "25" }] },
  { day: 26, readings: [{ book: "Exodus", chapters: "9-10" }, { book: "Matthew", chapters: "26" }, { book: "Psalms", chapters: "26" }] },
  { day: 27, readings: [{ book: "Exodus", chapters: "11-12" }, { book: "Matthew", chapters: "27" }, { book: "Psalms", chapters: "27" }] },
  { day: 28, readings: [{ book: "Exodus", chapters: "13-14" }, { book: "Matthew", chapters: "28" }, { book: "Psalms", chapters: "28" }] },
  { day: 29, readings: [{ book: "Exodus", chapters: "15-16" }, { book: "Mark", chapters: "1" }, { book: "Psalms", chapters: "29" }] },
  { day: 30, readings: [{ book: "Exodus", chapters: "17-19" }, { book: "Mark", chapters: "2" }, { book: "Psalms", chapters: "30" }] },
  { day: 31, readings: [{ book: "Exodus", chapters: "20-21" }, { book: "Mark", chapters: "3" }, { book: "Psalms", chapters: "31" }] },
  // February (Days 32-59)
  { day: 32, readings: [{ book: "Exodus", chapters: "22-23" }, { book: "Mark", chapters: "4" }, { book: "Psalms", chapters: "32" }] },
  { day: 33, readings: [{ book: "Exodus", chapters: "24-26" }, { book: "Mark", chapters: "5" }, { book: "Psalms", chapters: "33" }] },
  { day: 34, readings: [{ book: "Exodus", chapters: "27-28" }, { book: "Mark", chapters: "6" }, { book: "Psalms", chapters: "34" }] },
  { day: 35, readings: [{ book: "Exodus", chapters: "29-30" }, { book: "Mark", chapters: "7" }, { book: "Psalms", chapters: "35" }] },
  { day: 36, readings: [{ book: "Exodus", chapters: "31-33" }, { book: "Mark", chapters: "8" }, { book: "Psalms", chapters: "36" }] },
  { day: 37, readings: [{ book: "Exodus", chapters: "34-35" }, { book: "Mark", chapters: "9" }, { book: "Psalms", chapters: "37" }] },
  { day: 38, readings: [{ book: "Exodus", chapters: "36-38" }, { book: "Mark", chapters: "10" }, { book: "Psalms", chapters: "38" }] },
  { day: 39, readings: [{ book: "Exodus", chapters: "39-40" }, { book: "Mark", chapters: "11" }, { book: "Psalms", chapters: "39" }] },
  { day: 40, readings: [{ book: "Leviticus", chapters: "1-3" }, { book: "Mark", chapters: "12" }, { book: "Psalms", chapters: "40" }] },
  { day: 41, readings: [{ book: "Leviticus", chapters: "4-5" }, { book: "Mark", chapters: "13" }, { book: "Psalms", chapters: "41" }] },
  { day: 42, readings: [{ book: "Leviticus", chapters: "6-7" }, { book: "Mark", chapters: "14" }, { book: "Psalms", chapters: "42" }] },
  { day: 43, readings: [{ book: "Leviticus", chapters: "8-10" }, { book: "Mark", chapters: "15" }, { book: "Psalms", chapters: "43" }] },
  { day: 44, readings: [{ book: "Leviticus", chapters: "11-12" }, { book: "Mark", chapters: "16" }, { book: "Psalms", chapters: "44" }] },
  { day: 45, readings: [{ book: "Leviticus", chapters: "13" }, { book: "Luke", chapters: "1" }, { book: "Psalms", chapters: "45" }] },
  { day: 46, readings: [{ book: "Leviticus", chapters: "14" }, { book: "Luke", chapters: "2" }, { book: "Psalms", chapters: "46" }] },
  { day: 47, readings: [{ book: "Leviticus", chapters: "15-16" }, { book: "Luke", chapters: "3" }, { book: "Psalms", chapters: "47" }] },
  { day: 48, readings: [{ book: "Leviticus", chapters: "17-18" }, { book: "Luke", chapters: "4" }, { book: "Psalms", chapters: "48" }] },
  { day: 49, readings: [{ book: "Leviticus", chapters: "19-20" }, { book: "Luke", chapters: "5" }, { book: "Psalms", chapters: "49" }] },
  { day: 50, readings: [{ book: "Leviticus", chapters: "21-22" }, { book: "Luke", chapters: "6" }, { book: "Psalms", chapters: "50" }] },
  { day: 51, readings: [{ book: "Leviticus", chapters: "23-24" }, { book: "Luke", chapters: "7" }, { book: "Psalms", chapters: "51" }] },
  { day: 52, readings: [{ book: "Leviticus", chapters: "25" }, { book: "Luke", chapters: "8" }, { book: "Psalms", chapters: "52" }] },
  { day: 53, readings: [{ book: "Leviticus", chapters: "26-27" }, { book: "Luke", chapters: "9" }, { book: "Psalms", chapters: "53" }] },
  { day: 54, readings: [{ book: "Numbers", chapters: "1-2" }, { book: "Luke", chapters: "10" }, { book: "Psalms", chapters: "54" }] },
  { day: 55, readings: [{ book: "Numbers", chapters: "3-4" }, { book: "Luke", chapters: "11" }, { book: "Psalms", chapters: "55" }] },
  { day: 56, readings: [{ book: "Numbers", chapters: "5-6" }, { book: "Luke", chapters: "12" }, { book: "Psalms", chapters: "56" }] },
  { day: 57, readings: [{ book: "Numbers", chapters: "7" }, { book: "Luke", chapters: "13" }, { book: "Psalms", chapters: "57" }] },
  { day: 58, readings: [{ book: "Numbers", chapters: "8-10" }, { book: "Luke", chapters: "14" }, { book: "Psalms", chapters: "58" }] },
  { day: 59, readings: [{ book: "Numbers", chapters: "11-12" }, { book: "Luke", chapters: "15" }, { book: "Psalms", chapters: "59" }] },
  // March (Days 60-90)
  { day: 60, readings: [{ book: "Numbers", chapters: "13-14" }, { book: "Luke", chapters: "16" }, { book: "Psalms", chapters: "60" }] },
  { day: 61, readings: [{ book: "Numbers", chapters: "15-16" }, { book: "Luke", chapters: "17" }, { book: "Psalms", chapters: "61" }] },
  { day: 62, readings: [{ book: "Numbers", chapters: "17-18" }, { book: "Luke", chapters: "18" }, { book: "Psalms", chapters: "62" }] },
  { day: 63, readings: [{ book: "Numbers", chapters: "19-20" }, { book: "Luke", chapters: "19" }, { book: "Psalms", chapters: "63" }] },
  { day: 64, readings: [{ book: "Numbers", chapters: "21-22" }, { book: "Luke", chapters: "20" }, { book: "Psalms", chapters: "64" }] },
  { day: 65, readings: [{ book: "Numbers", chapters: "23-25" }, { book: "Luke", chapters: "21" }, { book: "Psalms", chapters: "65" }] },
  { day: 66, readings: [{ book: "Numbers", chapters: "26-27" }, { book: "Luke", chapters: "22" }, { book: "Psalms", chapters: "66" }] },
  { day: 67, readings: [{ book: "Numbers", chapters: "28-29" }, { book: "Luke", chapters: "23" }, { book: "Psalms", chapters: "67" }] },
  { day: 68, readings: [{ book: "Numbers", chapters: "30-31" }, { book: "Luke", chapters: "24" }, { book: "Psalms", chapters: "68" }] },
  { day: 69, readings: [{ book: "Numbers", chapters: "32-33" }, { book: "John", chapters: "1" }, { book: "Psalms", chapters: "69" }] },
  { day: 70, readings: [{ book: "Numbers", chapters: "34-36" }, { book: "John", chapters: "2" }, { book: "Psalms", chapters: "70" }] },
  { day: 71, readings: [{ book: "Deuteronomy", chapters: "1-2" }, { book: "John", chapters: "3" }, { book: "Psalms", chapters: "71" }] },
  { day: 72, readings: [{ book: "Deuteronomy", chapters: "3-4" }, { book: "John", chapters: "4" }, { book: "Psalms", chapters: "72" }] },
  { day: 73, readings: [{ book: "Deuteronomy", chapters: "5-6" }, { book: "John", chapters: "5" }, { book: "Psalms", chapters: "73" }] },
  { day: 74, readings: [{ book: "Deuteronomy", chapters: "7-9" }, { book: "John", chapters: "6" }, { book: "Psalms", chapters: "74" }] },
  { day: 75, readings: [{ book: "Deuteronomy", chapters: "10-12" }, { book: "John", chapters: "7" }, { book: "Psalms", chapters: "75" }] },
  { day: 76, readings: [{ book: "Deuteronomy", chapters: "13-15" }, { book: "John", chapters: "8" }, { book: "Psalms", chapters: "76" }] },
  { day: 77, readings: [{ book: "Deuteronomy", chapters: "16-18" }, { book: "John", chapters: "9" }, { book: "Psalms", chapters: "77" }] },
  { day: 78, readings: [{ book: "Deuteronomy", chapters: "19-21" }, { book: "John", chapters: "10" }, { book: "Psalms", chapters: "78" }] },
  { day: 79, readings: [{ book: "Deuteronomy", chapters: "22-24" }, { book: "John", chapters: "11" }, { book: "Psalms", chapters: "79" }] },
  { day: 80, readings: [{ book: "Deuteronomy", chapters: "25-27" }, { book: "John", chapters: "12" }, { book: "Psalms", chapters: "80" }] },
  { day: 81, readings: [{ book: "Deuteronomy", chapters: "28" }, { book: "John", chapters: "13" }, { book: "Psalms", chapters: "81" }] },
  { day: 82, readings: [{ book: "Deuteronomy", chapters: "29-30" }, { book: "John", chapters: "14" }, { book: "Psalms", chapters: "82" }] },
  { day: 83, readings: [{ book: "Deuteronomy", chapters: "31-32" }, { book: "John", chapters: "15" }, { book: "Psalms", chapters: "83" }] },
  { day: 84, readings: [{ book: "Deuteronomy", chapters: "33-34" }, { book: "John", chapters: "16" }, { book: "Psalms", chapters: "84" }] },
  { day: 85, readings: [{ book: "Joshua", chapters: "1-3" }, { book: "John", chapters: "17" }, { book: "Psalms", chapters: "85" }] },
  { day: 86, readings: [{ book: "Joshua", chapters: "4-6" }, { book: "John", chapters: "18" }, { book: "Psalms", chapters: "86" }] },
  { day: 87, readings: [{ book: "Joshua", chapters: "7-8" }, { book: "John", chapters: "19" }, { book: "Psalms", chapters: "87" }] },
  { day: 88, readings: [{ book: "Joshua", chapters: "9-10" }, { book: "John", chapters: "20" }, { book: "Psalms", chapters: "88" }] },
  { day: 89, readings: [{ book: "Joshua", chapters: "11-13" }, { book: "John", chapters: "21" }, { book: "Psalms", chapters: "89" }] },
  { day: 90, readings: [{ book: "Joshua", chapters: "14-16" }, { book: "Acts", chapters: "1" }, { book: "Psalms", chapters: "90" }] },
  // April (Days 91-120)
  { day: 91, readings: [{ book: "Joshua", chapters: "17-19" }, { book: "Acts", chapters: "2" }, { book: "Psalms", chapters: "91" }] },
  { day: 92, readings: [{ book: "Joshua", chapters: "20-22" }, { book: "Acts", chapters: "3" }, { book: "Psalms", chapters: "92" }] },
  { day: 93, readings: [{ book: "Joshua", chapters: "23-24" }, { book: "Acts", chapters: "4" }, { book: "Psalms", chapters: "93" }] },
  { day: 94, readings: [{ book: "Judges", chapters: "1-2" }, { book: "Acts", chapters: "5" }, { book: "Psalms", chapters: "94" }] },
  { day: 95, readings: [{ book: "Judges", chapters: "3-5" }, { book: "Acts", chapters: "6" }, { book: "Psalms", chapters: "95" }] },
  { day: 96, readings: [{ book: "Judges", chapters: "6-7" }, { book: "Acts", chapters: "7" }, { book: "Psalms", chapters: "96" }] },
  { day: 97, readings: [{ book: "Judges", chapters: "8-9" }, { book: "Acts", chapters: "8" }, { book: "Psalms", chapters: "97" }] },
  { day: 98, readings: [{ book: "Judges", chapters: "10-12" }, { book: "Acts", chapters: "9" }, { book: "Psalms", chapters: "98" }] },
  { day: 99, readings: [{ book: "Judges", chapters: "13-15" }, { book: "Acts", chapters: "10" }, { book: "Psalms", chapters: "99" }] },
  { day: 100, readings: [{ book: "Judges", chapters: "16-18" }, { book: "Acts", chapters: "11" }, { book: "Psalms", chapters: "100" }] },
  { day: 101, readings: [{ book: "Judges", chapters: "19-21" }, { book: "Acts", chapters: "12" }, { book: "Psalms", chapters: "101" }] },
  { day: 102, readings: [{ book: "Ruth", chapters: "1-4" }, { book: "Acts", chapters: "13" }, { book: "Psalms", chapters: "102" }] },
  { day: 103, readings: [{ book: "1 Samuel", chapters: "1-3" }, { book: "Acts", chapters: "14" }, { book: "Psalms", chapters: "103" }] },
  { day: 104, readings: [{ book: "1 Samuel", chapters: "4-6" }, { book: "Acts", chapters: "15" }, { book: "Psalms", chapters: "104" }] },
  { day: 105, readings: [{ book: "1 Samuel", chapters: "7-9" }, { book: "Acts", chapters: "16" }, { book: "Psalms", chapters: "105" }] },
  { day: 106, readings: [{ book: "1 Samuel", chapters: "10-12" }, { book: "Acts", chapters: "17" }, { book: "Psalms", chapters: "106" }] },
  { day: 107, readings: [{ book: "1 Samuel", chapters: "13-14" }, { book: "Acts", chapters: "18" }, { book: "Psalms", chapters: "107" }] },
  { day: 108, readings: [{ book: "1 Samuel", chapters: "15-16" }, { book: "Acts", chapters: "19" }, { book: "Psalms", chapters: "108" }] },
  { day: 109, readings: [{ book: "1 Samuel", chapters: "17-18" }, { book: "Acts", chapters: "20" }, { book: "Psalms", chapters: "109" }] },
  { day: 110, readings: [{ book: "1 Samuel", chapters: "19-21" }, { book: "Acts", chapters: "21" }, { book: "Psalms", chapters: "110" }] },
  { day: 111, readings: [{ book: "1 Samuel", chapters: "22-24" }, { book: "Acts", chapters: "22" }, { book: "Psalms", chapters: "111" }] },
  { day: 112, readings: [{ book: "1 Samuel", chapters: "25-26" }, { book: "Acts", chapters: "23" }, { book: "Psalms", chapters: "112" }] },
  { day: 113, readings: [{ book: "1 Samuel", chapters: "27-29" }, { book: "Acts", chapters: "24" }, { book: "Psalms", chapters: "113" }] },
  { day: 114, readings: [{ book: "1 Samuel", chapters: "30-31" }, { book: "Acts", chapters: "25" }, { book: "Psalms", chapters: "114" }] },
  { day: 115, readings: [{ book: "2 Samuel", chapters: "1-2" }, { book: "Acts", chapters: "26" }, { book: "Psalms", chapters: "115" }] },
  { day: 116, readings: [{ book: "2 Samuel", chapters: "3-5" }, { book: "Acts", chapters: "27" }, { book: "Psalms", chapters: "116" }] },
  { day: 117, readings: [{ book: "2 Samuel", chapters: "6-8" }, { book: "Acts", chapters: "28" }, { book: "Psalms", chapters: "117" }] },
  { day: 118, readings: [{ book: "2 Samuel", chapters: "9-11" }, { book: "Romans", chapters: "1" }, { book: "Psalms", chapters: "118" }] },
  { day: 119, readings: [{ book: "2 Samuel", chapters: "12-13" }, { book: "Romans", chapters: "2" }, { book: "Psalms", chapters: "119:1-24" }] },
  { day: 120, readings: [{ book: "2 Samuel", chapters: "14-15" }, { book: "Romans", chapters: "3" }, { book: "Psalms", chapters: "119:25-48" }] },
  // May-December (Days 121-365) - Continued schedule
  { day: 121, readings: [{ book: "2 Samuel", chapters: "16-17" }, { book: "Romans", chapters: "4" }, { book: "Psalms", chapters: "119:49-72" }] },
  { day: 122, readings: [{ book: "2 Samuel", chapters: "18-19" }, { book: "Romans", chapters: "5" }, { book: "Psalms", chapters: "119:73-96" }] },
  { day: 123, readings: [{ book: "2 Samuel", chapters: "20-21" }, { book: "Romans", chapters: "6" }, { book: "Psalms", chapters: "119:97-120" }] },
  { day: 124, readings: [{ book: "2 Samuel", chapters: "22-24" }, { book: "Romans", chapters: "7" }, { book: "Psalms", chapters: "119:121-144" }] },
  { day: 125, readings: [{ book: "1 Kings", chapters: "1-2" }, { book: "Romans", chapters: "8" }, { book: "Psalms", chapters: "119:145-176" }] },
  { day: 126, readings: [{ book: "1 Kings", chapters: "3-4" }, { book: "Romans", chapters: "9" }, { book: "Psalms", chapters: "120" }] },
  { day: 127, readings: [{ book: "1 Kings", chapters: "5-6" }, { book: "Romans", chapters: "10" }, { book: "Psalms", chapters: "121" }] },
  { day: 128, readings: [{ book: "1 Kings", chapters: "7-8" }, { book: "Romans", chapters: "11" }, { book: "Psalms", chapters: "122" }] },
  { day: 129, readings: [{ book: "1 Kings", chapters: "9-10" }, { book: "Romans", chapters: "12" }, { book: "Psalms", chapters: "123" }] },
  { day: 130, readings: [{ book: "1 Kings", chapters: "11-12" }, { book: "Romans", chapters: "13" }, { book: "Psalms", chapters: "124" }] },
  { day: 131, readings: [{ book: "1 Kings", chapters: "13-14" }, { book: "Romans", chapters: "14" }, { book: "Psalms", chapters: "125" }] },
  { day: 132, readings: [{ book: "1 Kings", chapters: "15-16" }, { book: "Romans", chapters: "15" }, { book: "Psalms", chapters: "126" }] },
  { day: 133, readings: [{ book: "1 Kings", chapters: "17-18" }, { book: "Romans", chapters: "16" }, { book: "Psalms", chapters: "127" }] },
  { day: 134, readings: [{ book: "1 Kings", chapters: "19-20" }, { book: "1 Corinthians", chapters: "1" }, { book: "Psalms", chapters: "128" }] },
  { day: 135, readings: [{ book: "1 Kings", chapters: "21-22" }, { book: "1 Corinthians", chapters: "2" }, { book: "Psalms", chapters: "129" }] },
  { day: 136, readings: [{ book: "2 Kings", chapters: "1-3" }, { book: "1 Corinthians", chapters: "3" }, { book: "Psalms", chapters: "130" }] },
  { day: 137, readings: [{ book: "2 Kings", chapters: "4-5" }, { book: "1 Corinthians", chapters: "4" }, { book: "Psalms", chapters: "131" }] },
  { day: 138, readings: [{ book: "2 Kings", chapters: "6-8" }, { book: "1 Corinthians", chapters: "5" }, { book: "Psalms", chapters: "132" }] },
  { day: 139, readings: [{ book: "2 Kings", chapters: "9-10" }, { book: "1 Corinthians", chapters: "6" }, { book: "Psalms", chapters: "133" }] },
  { day: 140, readings: [{ book: "2 Kings", chapters: "11-13" }, { book: "1 Corinthians", chapters: "7" }, { book: "Psalms", chapters: "134" }] },
  { day: 141, readings: [{ book: "2 Kings", chapters: "14-15" }, { book: "1 Corinthians", chapters: "8" }, { book: "Psalms", chapters: "135" }] },
  { day: 142, readings: [{ book: "2 Kings", chapters: "16-17" }, { book: "1 Corinthians", chapters: "9" }, { book: "Psalms", chapters: "136" }] },
  { day: 143, readings: [{ book: "2 Kings", chapters: "18-19" }, { book: "1 Corinthians", chapters: "10" }, { book: "Psalms", chapters: "137" }] },
  { day: 144, readings: [{ book: "2 Kings", chapters: "20-22" }, { book: "1 Corinthians", chapters: "11" }, { book: "Psalms", chapters: "138" }] },
  { day: 145, readings: [{ book: "2 Kings", chapters: "23-25" }, { book: "1 Corinthians", chapters: "12" }, { book: "Psalms", chapters: "139" }] },
  { day: 146, readings: [{ book: "1 Chronicles", chapters: "1-2" }, { book: "1 Corinthians", chapters: "13" }, { book: "Psalms", chapters: "140" }] },
  { day: 147, readings: [{ book: "1 Chronicles", chapters: "3-5" }, { book: "1 Corinthians", chapters: "14" }, { book: "Psalms", chapters: "141" }] },
  { day: 148, readings: [{ book: "1 Chronicles", chapters: "6-7" }, { book: "1 Corinthians", chapters: "15" }, { book: "Psalms", chapters: "142" }] },
  { day: 149, readings: [{ book: "1 Chronicles", chapters: "8-10" }, { book: "1 Corinthians", chapters: "16" }, { book: "Psalms", chapters: "143" }] },
  { day: 150, readings: [{ book: "1 Chronicles", chapters: "11-13" }, { book: "2 Corinthians", chapters: "1" }, { book: "Psalms", chapters: "144" }] },
  { day: 151, readings: [{ book: "1 Chronicles", chapters: "14-16" }, { book: "2 Corinthians", chapters: "2" }, { book: "Psalms", chapters: "145" }] },
  { day: 152, readings: [{ book: "1 Chronicles", chapters: "17-19" }, { book: "2 Corinthians", chapters: "3" }, { book: "Psalms", chapters: "146" }] },
  { day: 153, readings: [{ book: "1 Chronicles", chapters: "20-22" }, { book: "2 Corinthians", chapters: "4" }, { book: "Psalms", chapters: "147" }] },
  { day: 154, readings: [{ book: "1 Chronicles", chapters: "23-25" }, { book: "2 Corinthians", chapters: "5" }, { book: "Psalms", chapters: "148" }] },
  { day: 155, readings: [{ book: "1 Chronicles", chapters: "26-27" }, { book: "2 Corinthians", chapters: "6" }, { book: "Psalms", chapters: "149" }] },
  { day: 156, readings: [{ book: "1 Chronicles", chapters: "28-29" }, { book: "2 Corinthians", chapters: "7" }, { book: "Psalms", chapters: "150" }] },
  { day: 157, readings: [{ book: "2 Chronicles", chapters: "1-3" }, { book: "2 Corinthians", chapters: "8" }, { book: "Proverbs", chapters: "1" }] },
  { day: 158, readings: [{ book: "2 Chronicles", chapters: "4-6" }, { book: "2 Corinthians", chapters: "9" }, { book: "Proverbs", chapters: "2" }] },
  { day: 159, readings: [{ book: "2 Chronicles", chapters: "7-9" }, { book: "2 Corinthians", chapters: "10" }, { book: "Proverbs", chapters: "3" }] },
  { day: 160, readings: [{ book: "2 Chronicles", chapters: "10-12" }, { book: "2 Corinthians", chapters: "11" }, { book: "Proverbs", chapters: "4" }] },
  { day: 161, readings: [{ book: "2 Chronicles", chapters: "13-15" }, { book: "2 Corinthians", chapters: "12" }, { book: "Proverbs", chapters: "5" }] },
  { day: 162, readings: [{ book: "2 Chronicles", chapters: "16-18" }, { book: "2 Corinthians", chapters: "13" }, { book: "Proverbs", chapters: "6" }] },
  { day: 163, readings: [{ book: "2 Chronicles", chapters: "19-21" }, { book: "Galatians", chapters: "1" }, { book: "Proverbs", chapters: "7" }] },
  { day: 164, readings: [{ book: "2 Chronicles", chapters: "22-24" }, { book: "Galatians", chapters: "2" }, { book: "Proverbs", chapters: "8" }] },
  { day: 165, readings: [{ book: "2 Chronicles", chapters: "25-27" }, { book: "Galatians", chapters: "3" }, { book: "Proverbs", chapters: "9" }] },
  { day: 166, readings: [{ book: "2 Chronicles", chapters: "28-29" }, { book: "Galatians", chapters: "4" }, { book: "Proverbs", chapters: "10" }] },
  { day: 167, readings: [{ book: "2 Chronicles", chapters: "30-31" }, { book: "Galatians", chapters: "5" }, { book: "Proverbs", chapters: "11" }] },
  { day: 168, readings: [{ book: "2 Chronicles", chapters: "32-33" }, { book: "Galatians", chapters: "6" }, { book: "Proverbs", chapters: "12" }] },
  { day: 169, readings: [{ book: "2 Chronicles", chapters: "34-36" }, { book: "Ephesians", chapters: "1" }, { book: "Proverbs", chapters: "13" }] },
  { day: 170, readings: [{ book: "Ezra", chapters: "1-2" }, { book: "Ephesians", chapters: "2" }, { book: "Proverbs", chapters: "14" }] },
  { day: 171, readings: [{ book: "Ezra", chapters: "3-5" }, { book: "Ephesians", chapters: "3" }, { book: "Proverbs", chapters: "15" }] },
  { day: 172, readings: [{ book: "Ezra", chapters: "6-8" }, { book: "Ephesians", chapters: "4" }, { book: "Proverbs", chapters: "16" }] },
  { day: 173, readings: [{ book: "Ezra", chapters: "9-10" }, { book: "Ephesians", chapters: "5" }, { book: "Proverbs", chapters: "17" }] },
  { day: 174, readings: [{ book: "Nehemiah", chapters: "1-3" }, { book: "Ephesians", chapters: "6" }, { book: "Proverbs", chapters: "18" }] },
  { day: 175, readings: [{ book: "Nehemiah", chapters: "4-6" }, { book: "Philippians", chapters: "1" }, { book: "Proverbs", chapters: "19" }] },
  { day: 176, readings: [{ book: "Nehemiah", chapters: "7-8" }, { book: "Philippians", chapters: "2" }, { book: "Proverbs", chapters: "20" }] },
  { day: 177, readings: [{ book: "Nehemiah", chapters: "9-10" }, { book: "Philippians", chapters: "3" }, { book: "Proverbs", chapters: "21" }] },
  { day: 178, readings: [{ book: "Nehemiah", chapters: "11-13" }, { book: "Philippians", chapters: "4" }, { book: "Proverbs", chapters: "22" }] },
  { day: 179, readings: [{ book: "Esther", chapters: "1-3" }, { book: "Colossians", chapters: "1" }, { book: "Proverbs", chapters: "23" }] },
  { day: 180, readings: [{ book: "Esther", chapters: "4-6" }, { book: "Colossians", chapters: "2" }, { book: "Proverbs", chapters: "24" }] },
  { day: 181, readings: [{ book: "Esther", chapters: "7-10" }, { book: "Colossians", chapters: "3" }, { book: "Proverbs", chapters: "25" }] },
  { day: 182, readings: [{ book: "Job", chapters: "1-3" }, { book: "Colossians", chapters: "4" }, { book: "Proverbs", chapters: "26" }] },
  { day: 183, readings: [{ book: "Job", chapters: "4-6" }, { book: "1 Thessalonians", chapters: "1" }, { book: "Proverbs", chapters: "27" }] },
  { day: 184, readings: [{ book: "Job", chapters: "7-9" }, { book: "1 Thessalonians", chapters: "2" }, { book: "Proverbs", chapters: "28" }] },
  { day: 185, readings: [{ book: "Job", chapters: "10-13" }, { book: "1 Thessalonians", chapters: "3" }, { book: "Proverbs", chapters: "29" }] },
  { day: 186, readings: [{ book: "Job", chapters: "14-16" }, { book: "1 Thessalonians", chapters: "4" }, { book: "Proverbs", chapters: "30" }] },
  { day: 187, readings: [{ book: "Job", chapters: "17-20" }, { book: "1 Thessalonians", chapters: "5" }, { book: "Proverbs", chapters: "31" }] },
  { day: 188, readings: [{ book: "Job", chapters: "21-23" }, { book: "2 Thessalonians", chapters: "1" }, { book: "Ecclesiastes", chapters: "1" }] },
  { day: 189, readings: [{ book: "Job", chapters: "24-27" }, { book: "2 Thessalonians", chapters: "2" }, { book: "Ecclesiastes", chapters: "2" }] },
  { day: 190, readings: [{ book: "Job", chapters: "28-30" }, { book: "2 Thessalonians", chapters: "3" }, { book: "Ecclesiastes", chapters: "3" }] },
  { day: 191, readings: [{ book: "Job", chapters: "31-33" }, { book: "1 Timothy", chapters: "1" }, { book: "Ecclesiastes", chapters: "4" }] },
  { day: 192, readings: [{ book: "Job", chapters: "34-36" }, { book: "1 Timothy", chapters: "2" }, { book: "Ecclesiastes", chapters: "5" }] },
  { day: 193, readings: [{ book: "Job", chapters: "37-39" }, { book: "1 Timothy", chapters: "3" }, { book: "Ecclesiastes", chapters: "6" }] },
  { day: 194, readings: [{ book: "Job", chapters: "40-42" }, { book: "1 Timothy", chapters: "4" }, { book: "Ecclesiastes", chapters: "7" }] },
  { day: 195, readings: [{ book: "Psalms", chapters: "1-3" }, { book: "1 Timothy", chapters: "5" }, { book: "Ecclesiastes", chapters: "8" }] },
  { day: 196, readings: [{ book: "Psalms", chapters: "4-6" }, { book: "1 Timothy", chapters: "6" }, { book: "Ecclesiastes", chapters: "9" }] },
  { day: 197, readings: [{ book: "Psalms", chapters: "7-9" }, { book: "2 Timothy", chapters: "1" }, { book: "Ecclesiastes", chapters: "10" }] },
  { day: 198, readings: [{ book: "Psalms", chapters: "10-12" }, { book: "2 Timothy", chapters: "2" }, { book: "Ecclesiastes", chapters: "11" }] },
  { day: 199, readings: [{ book: "Psalms", chapters: "13-16" }, { book: "2 Timothy", chapters: "3" }, { book: "Ecclesiastes", chapters: "12" }] },
  { day: 200, readings: [{ book: "Psalms", chapters: "17-18" }, { book: "2 Timothy", chapters: "4" }, { book: "Song of Solomon", chapters: "1" }] },
  { day: 201, readings: [{ book: "Psalms", chapters: "19-21" }, { book: "Titus", chapters: "1" }, { book: "Song of Solomon", chapters: "2" }] },
  { day: 202, readings: [{ book: "Psalms", chapters: "22-24" }, { book: "Titus", chapters: "2" }, { book: "Song of Solomon", chapters: "3" }] },
  { day: 203, readings: [{ book: "Psalms", chapters: "25-27" }, { book: "Titus", chapters: "3" }, { book: "Song of Solomon", chapters: "4" }] },
  { day: 204, readings: [{ book: "Psalms", chapters: "28-30" }, { book: "Philemon", chapters: "1" }, { book: "Song of Solomon", chapters: "5" }] },
  { day: 205, readings: [{ book: "Psalms", chapters: "31-33" }, { book: "Hebrews", chapters: "1" }, { book: "Song of Solomon", chapters: "6" }] },
  { day: 206, readings: [{ book: "Psalms", chapters: "34-35" }, { book: "Hebrews", chapters: "2" }, { book: "Song of Solomon", chapters: "7" }] },
  { day: 207, readings: [{ book: "Psalms", chapters: "36-37" }, { book: "Hebrews", chapters: "3" }, { book: "Song of Solomon", chapters: "8" }] },
  { day: 208, readings: [{ book: "Psalms", chapters: "38-40" }, { book: "Hebrews", chapters: "4" }, { book: "Isaiah", chapters: "1" }] },
  { day: 209, readings: [{ book: "Psalms", chapters: "41-43" }, { book: "Hebrews", chapters: "5" }, { book: "Isaiah", chapters: "2" }] },
  { day: 210, readings: [{ book: "Psalms", chapters: "44-46" }, { book: "Hebrews", chapters: "6" }, { book: "Isaiah", chapters: "3-4" }] },
  { day: 211, readings: [{ book: "Psalms", chapters: "47-49" }, { book: "Hebrews", chapters: "7" }, { book: "Isaiah", chapters: "5" }] },
  { day: 212, readings: [{ book: "Psalms", chapters: "50-52" }, { book: "Hebrews", chapters: "8" }, { book: "Isaiah", chapters: "6" }] },
  { day: 213, readings: [{ book: "Psalms", chapters: "53-55" }, { book: "Hebrews", chapters: "9" }, { book: "Isaiah", chapters: "7" }] },
  { day: 214, readings: [{ book: "Psalms", chapters: "56-58" }, { book: "Hebrews", chapters: "10" }, { book: "Isaiah", chapters: "8-9" }] },
  { day: 215, readings: [{ book: "Psalms", chapters: "59-61" }, { book: "Hebrews", chapters: "11" }, { book: "Isaiah", chapters: "10" }] },
  { day: 216, readings: [{ book: "Psalms", chapters: "62-64" }, { book: "Hebrews", chapters: "12" }, { book: "Isaiah", chapters: "11-12" }] },
  { day: 217, readings: [{ book: "Psalms", chapters: "65-67" }, { book: "Hebrews", chapters: "13" }, { book: "Isaiah", chapters: "13" }] },
  { day: 218, readings: [{ book: "Psalms", chapters: "68-69" }, { book: "James", chapters: "1" }, { book: "Isaiah", chapters: "14" }] },
  { day: 219, readings: [{ book: "Psalms", chapters: "70-72" }, { book: "James", chapters: "2" }, { book: "Isaiah", chapters: "15-16" }] },
  { day: 220, readings: [{ book: "Psalms", chapters: "73-74" }, { book: "James", chapters: "3" }, { book: "Isaiah", chapters: "17-18" }] },
  { day: 221, readings: [{ book: "Psalms", chapters: "75-77" }, { book: "James", chapters: "4" }, { book: "Isaiah", chapters: "19-20" }] },
  { day: 222, readings: [{ book: "Psalms", chapters: "78" }, { book: "James", chapters: "5" }, { book: "Isaiah", chapters: "21" }] },
  { day: 223, readings: [{ book: "Psalms", chapters: "79-81" }, { book: "1 Peter", chapters: "1" }, { book: "Isaiah", chapters: "22" }] },
  { day: 224, readings: [{ book: "Psalms", chapters: "82-84" }, { book: "1 Peter", chapters: "2" }, { book: "Isaiah", chapters: "23" }] },
  { day: 225, readings: [{ book: "Psalms", chapters: "85-87" }, { book: "1 Peter", chapters: "3" }, { book: "Isaiah", chapters: "24" }] },
  { day: 226, readings: [{ book: "Psalms", chapters: "88-89" }, { book: "1 Peter", chapters: "4" }, { book: "Isaiah", chapters: "25-26" }] },
  { day: 227, readings: [{ book: "Psalms", chapters: "90-92" }, { book: "1 Peter", chapters: "5" }, { book: "Isaiah", chapters: "27" }] },
  { day: 228, readings: [{ book: "Psalms", chapters: "93-95" }, { book: "2 Peter", chapters: "1" }, { book: "Isaiah", chapters: "28" }] },
  { day: 229, readings: [{ book: "Psalms", chapters: "96-98" }, { book: "2 Peter", chapters: "2" }, { book: "Isaiah", chapters: "29" }] },
  { day: 230, readings: [{ book: "Psalms", chapters: "99-102" }, { book: "2 Peter", chapters: "3" }, { book: "Isaiah", chapters: "30" }] },
  { day: 231, readings: [{ book: "Psalms", chapters: "103-104" }, { book: "1 John", chapters: "1" }, { book: "Isaiah", chapters: "31-32" }] },
  { day: 232, readings: [{ book: "Psalms", chapters: "105-106" }, { book: "1 John", chapters: "2" }, { book: "Isaiah", chapters: "33" }] },
  { day: 233, readings: [{ book: "Psalms", chapters: "107-108" }, { book: "1 John", chapters: "3" }, { book: "Isaiah", chapters: "34-35" }] },
  { day: 234, readings: [{ book: "Psalms", chapters: "109-111" }, { book: "1 John", chapters: "4" }, { book: "Isaiah", chapters: "36" }] },
  { day: 235, readings: [{ book: "Psalms", chapters: "112-115" }, { book: "1 John", chapters: "5" }, { book: "Isaiah", chapters: "37" }] },
  { day: 236, readings: [{ book: "Psalms", chapters: "116-118" }, { book: "2 John", chapters: "1" }, { book: "Isaiah", chapters: "38-39" }] },
  { day: 237, readings: [{ book: "Psalms", chapters: "119:1-88" }, { book: "3 John", chapters: "1" }, { book: "Isaiah", chapters: "40" }] },
  { day: 238, readings: [{ book: "Psalms", chapters: "119:89-176" }, { book: "Jude", chapters: "1" }, { book: "Isaiah", chapters: "41" }] },
  { day: 239, readings: [{ book: "Psalms", chapters: "120-123" }, { book: "Revelation", chapters: "1" }, { book: "Isaiah", chapters: "42" }] },
  { day: 240, readings: [{ book: "Psalms", chapters: "124-127" }, { book: "Revelation", chapters: "2" }, { book: "Isaiah", chapters: "43" }] },
  { day: 241, readings: [{ book: "Psalms", chapters: "128-131" }, { book: "Revelation", chapters: "3" }, { book: "Isaiah", chapters: "44" }] },
  { day: 242, readings: [{ book: "Psalms", chapters: "132-135" }, { book: "Revelation", chapters: "4" }, { book: "Isaiah", chapters: "45" }] },
  { day: 243, readings: [{ book: "Psalms", chapters: "136-138" }, { book: "Revelation", chapters: "5" }, { book: "Isaiah", chapters: "46-47" }] },
  { day: 244, readings: [{ book: "Psalms", chapters: "139-141" }, { book: "Revelation", chapters: "6" }, { book: "Isaiah", chapters: "48" }] },
  { day: 245, readings: [{ book: "Psalms", chapters: "142-144" }, { book: "Revelation", chapters: "7" }, { book: "Isaiah", chapters: "49" }] },
  { day: 246, readings: [{ book: "Psalms", chapters: "145-147" }, { book: "Revelation", chapters: "8" }, { book: "Isaiah", chapters: "50" }] },
  { day: 247, readings: [{ book: "Psalms", chapters: "148-150" }, { book: "Revelation", chapters: "9" }, { book: "Isaiah", chapters: "51" }] },
  { day: 248, readings: [{ book: "Proverbs", chapters: "1-2" }, { book: "Revelation", chapters: "10" }, { book: "Isaiah", chapters: "52-53" }] },
  { day: 249, readings: [{ book: "Proverbs", chapters: "3-4" }, { book: "Revelation", chapters: "11" }, { book: "Isaiah", chapters: "54-55" }] },
  { day: 250, readings: [{ book: "Proverbs", chapters: "5-6" }, { book: "Revelation", chapters: "12" }, { book: "Isaiah", chapters: "56-57" }] },
  { day: 251, readings: [{ book: "Proverbs", chapters: "7-8" }, { book: "Revelation", chapters: "13" }, { book: "Isaiah", chapters: "58-59" }] },
  { day: 252, readings: [{ book: "Proverbs", chapters: "9-10" }, { book: "Revelation", chapters: "14" }, { book: "Isaiah", chapters: "60-61" }] },
  { day: 253, readings: [{ book: "Proverbs", chapters: "11-12" }, { book: "Revelation", chapters: "15" }, { book: "Isaiah", chapters: "62-63" }] },
  { day: 254, readings: [{ book: "Proverbs", chapters: "13-14" }, { book: "Revelation", chapters: "16" }, { book: "Isaiah", chapters: "64-65" }] },
  { day: 255, readings: [{ book: "Proverbs", chapters: "15-16" }, { book: "Revelation", chapters: "17" }, { book: "Isaiah", chapters: "66" }] },
  { day: 256, readings: [{ book: "Proverbs", chapters: "17-18" }, { book: "Revelation", chapters: "18" }, { book: "Jeremiah", chapters: "1" }] },
  { day: 257, readings: [{ book: "Proverbs", chapters: "19-20" }, { book: "Revelation", chapters: "19" }, { book: "Jeremiah", chapters: "2" }] },
  { day: 258, readings: [{ book: "Proverbs", chapters: "21-22" }, { book: "Revelation", chapters: "20" }, { book: "Jeremiah", chapters: "3" }] },
  { day: 259, readings: [{ book: "Proverbs", chapters: "23-24" }, { book: "Revelation", chapters: "21" }, { book: "Jeremiah", chapters: "4" }] },
  { day: 260, readings: [{ book: "Proverbs", chapters: "25-26" }, { book: "Revelation", chapters: "22" }, { book: "Jeremiah", chapters: "5" }] },
  { day: 261, readings: [{ book: "Proverbs", chapters: "27-28" }, { book: "Matthew", chapters: "1-2" }, { book: "Jeremiah", chapters: "6" }] },
  { day: 262, readings: [{ book: "Proverbs", chapters: "29-31" }, { book: "Matthew", chapters: "3-4" }, { book: "Jeremiah", chapters: "7" }] },
  { day: 263, readings: [{ book: "Ecclesiastes", chapters: "1-3" }, { book: "Matthew", chapters: "5" }, { book: "Jeremiah", chapters: "8" }] },
  { day: 264, readings: [{ book: "Ecclesiastes", chapters: "4-6" }, { book: "Matthew", chapters: "6" }, { book: "Jeremiah", chapters: "9" }] },
  { day: 265, readings: [{ book: "Ecclesiastes", chapters: "7-9" }, { book: "Matthew", chapters: "7" }, { book: "Jeremiah", chapters: "10" }] },
  { day: 266, readings: [{ book: "Ecclesiastes", chapters: "10-12" }, { book: "Matthew", chapters: "8" }, { book: "Jeremiah", chapters: "11-12" }] },
  { day: 267, readings: [{ book: "Song of Solomon", chapters: "1-4" }, { book: "Matthew", chapters: "9" }, { book: "Jeremiah", chapters: "13" }] },
  { day: 268, readings: [{ book: "Song of Solomon", chapters: "5-8" }, { book: "Matthew", chapters: "10" }, { book: "Jeremiah", chapters: "14-15" }] },
  { day: 269, readings: [{ book: "Isaiah", chapters: "1-2" }, { book: "Matthew", chapters: "11" }, { book: "Jeremiah", chapters: "16-17" }] },
  { day: 270, readings: [{ book: "Isaiah", chapters: "3-5" }, { book: "Matthew", chapters: "12" }, { book: "Jeremiah", chapters: "18" }] },
  { day: 271, readings: [{ book: "Isaiah", chapters: "6-8" }, { book: "Matthew", chapters: "13" }, { book: "Jeremiah", chapters: "19-20" }] },
  { day: 272, readings: [{ book: "Isaiah", chapters: "9-10" }, { book: "Matthew", chapters: "14" }, { book: "Jeremiah", chapters: "21-22" }] },
  { day: 273, readings: [{ book: "Isaiah", chapters: "11-13" }, { book: "Matthew", chapters: "15" }, { book: "Jeremiah", chapters: "23" }] },
  { day: 274, readings: [{ book: "Isaiah", chapters: "14-16" }, { book: "Matthew", chapters: "16" }, { book: "Jeremiah", chapters: "24-25" }] },
  { day: 275, readings: [{ book: "Isaiah", chapters: "17-19" }, { book: "Matthew", chapters: "17" }, { book: "Jeremiah", chapters: "26" }] },
  { day: 276, readings: [{ book: "Isaiah", chapters: "20-22" }, { book: "Matthew", chapters: "18" }, { book: "Jeremiah", chapters: "27-28" }] },
  { day: 277, readings: [{ book: "Isaiah", chapters: "23-25" }, { book: "Matthew", chapters: "19" }, { book: "Jeremiah", chapters: "29" }] },
  { day: 278, readings: [{ book: "Isaiah", chapters: "26-27" }, { book: "Matthew", chapters: "20" }, { book: "Jeremiah", chapters: "30-31" }] },
  { day: 279, readings: [{ book: "Isaiah", chapters: "28-29" }, { book: "Matthew", chapters: "21" }, { book: "Jeremiah", chapters: "32" }] },
  { day: 280, readings: [{ book: "Isaiah", chapters: "30-31" }, { book: "Matthew", chapters: "22" }, { book: "Jeremiah", chapters: "33" }] },
  { day: 281, readings: [{ book: "Isaiah", chapters: "32-33" }, { book: "Matthew", chapters: "23" }, { book: "Jeremiah", chapters: "34-35" }] },
  { day: 282, readings: [{ book: "Isaiah", chapters: "34-36" }, { book: "Matthew", chapters: "24" }, { book: "Jeremiah", chapters: "36" }] },
  { day: 283, readings: [{ book: "Isaiah", chapters: "37-38" }, { book: "Matthew", chapters: "25" }, { book: "Jeremiah", chapters: "37-38" }] },
  { day: 284, readings: [{ book: "Isaiah", chapters: "39-40" }, { book: "Matthew", chapters: "26" }, { book: "Jeremiah", chapters: "39-40" }] },
  { day: 285, readings: [{ book: "Isaiah", chapters: "41-42" }, { book: "Matthew", chapters: "27" }, { book: "Jeremiah", chapters: "41-42" }] },
  { day: 286, readings: [{ book: "Isaiah", chapters: "43-44" }, { book: "Matthew", chapters: "28" }, { book: "Jeremiah", chapters: "43-44" }] },
  { day: 287, readings: [{ book: "Isaiah", chapters: "45-47" }, { book: "Mark", chapters: "1" }, { book: "Jeremiah", chapters: "45-46" }] },
  { day: 288, readings: [{ book: "Isaiah", chapters: "48-49" }, { book: "Mark", chapters: "2" }, { book: "Jeremiah", chapters: "47-48" }] },
  { day: 289, readings: [{ book: "Isaiah", chapters: "50-52" }, { book: "Mark", chapters: "3" }, { book: "Jeremiah", chapters: "49" }] },
  { day: 290, readings: [{ book: "Isaiah", chapters: "53-55" }, { book: "Mark", chapters: "4" }, { book: "Jeremiah", chapters: "50" }] },
  { day: 291, readings: [{ book: "Isaiah", chapters: "56-58" }, { book: "Mark", chapters: "5" }, { book: "Jeremiah", chapters: "51" }] },
  { day: 292, readings: [{ book: "Isaiah", chapters: "59-61" }, { book: "Mark", chapters: "6" }, { book: "Jeremiah", chapters: "52" }] },
  { day: 293, readings: [{ book: "Isaiah", chapters: "62-64" }, { book: "Mark", chapters: "7" }, { book: "Lamentations", chapters: "1" }] },
  { day: 294, readings: [{ book: "Isaiah", chapters: "65-66" }, { book: "Mark", chapters: "8" }, { book: "Lamentations", chapters: "2" }] },
  { day: 295, readings: [{ book: "Jeremiah", chapters: "1-2" }, { book: "Mark", chapters: "9" }, { book: "Lamentations", chapters: "3" }] },
  { day: 296, readings: [{ book: "Jeremiah", chapters: "3-4" }, { book: "Mark", chapters: "10" }, { book: "Lamentations", chapters: "4" }] },
  { day: 297, readings: [{ book: "Jeremiah", chapters: "5-6" }, { book: "Mark", chapters: "11" }, { book: "Lamentations", chapters: "5" }] },
  { day: 298, readings: [{ book: "Jeremiah", chapters: "7-8" }, { book: "Mark", chapters: "12" }, { book: "Ezekiel", chapters: "1" }] },
  { day: 299, readings: [{ book: "Jeremiah", chapters: "9-10" }, { book: "Mark", chapters: "13" }, { book: "Ezekiel", chapters: "2-3" }] },
  { day: 300, readings: [{ book: "Jeremiah", chapters: "11-13" }, { book: "Mark", chapters: "14" }, { book: "Ezekiel", chapters: "4-5" }] },
  { day: 301, readings: [{ book: "Jeremiah", chapters: "14-15" }, { book: "Mark", chapters: "15" }, { book: "Ezekiel", chapters: "6-7" }] },
  { day: 302, readings: [{ book: "Jeremiah", chapters: "16-17" }, { book: "Mark", chapters: "16" }, { book: "Ezekiel", chapters: "8-10" }] },
  { day: 303, readings: [{ book: "Jeremiah", chapters: "18-20" }, { book: "Luke", chapters: "1" }, { book: "Ezekiel", chapters: "11-12" }] },
  { day: 304, readings: [{ book: "Jeremiah", chapters: "21-22" }, { book: "Luke", chapters: "2" }, { book: "Ezekiel", chapters: "13-14" }] },
  { day: 305, readings: [{ book: "Jeremiah", chapters: "23-24" }, { book: "Luke", chapters: "3" }, { book: "Ezekiel", chapters: "15-16" }] },
  { day: 306, readings: [{ book: "Jeremiah", chapters: "25-26" }, { book: "Luke", chapters: "4" }, { book: "Ezekiel", chapters: "17" }] },
  { day: 307, readings: [{ book: "Jeremiah", chapters: "27-28" }, { book: "Luke", chapters: "5" }, { book: "Ezekiel", chapters: "18-19" }] },
  { day: 308, readings: [{ book: "Jeremiah", chapters: "29-30" }, { book: "Luke", chapters: "6" }, { book: "Ezekiel", chapters: "20" }] },
  { day: 309, readings: [{ book: "Jeremiah", chapters: "31-32" }, { book: "Luke", chapters: "7" }, { book: "Ezekiel", chapters: "21-22" }] },
  { day: 310, readings: [{ book: "Jeremiah", chapters: "33-35" }, { book: "Luke", chapters: "8" }, { book: "Ezekiel", chapters: "23" }] },
  { day: 311, readings: [{ book: "Jeremiah", chapters: "36-37" }, { book: "Luke", chapters: "9" }, { book: "Ezekiel", chapters: "24-25" }] },
  { day: 312, readings: [{ book: "Jeremiah", chapters: "38-39" }, { book: "Luke", chapters: "10" }, { book: "Ezekiel", chapters: "26-27" }] },
  { day: 313, readings: [{ book: "Jeremiah", chapters: "40-42" }, { book: "Luke", chapters: "11" }, { book: "Ezekiel", chapters: "28" }] },
  { day: 314, readings: [{ book: "Jeremiah", chapters: "43-45" }, { book: "Luke", chapters: "12" }, { book: "Ezekiel", chapters: "29-30" }] },
  { day: 315, readings: [{ book: "Jeremiah", chapters: "46-48" }, { book: "Luke", chapters: "13" }, { book: "Ezekiel", chapters: "31-32" }] },
  { day: 316, readings: [{ book: "Jeremiah", chapters: "49-50" }, { book: "Luke", chapters: "14" }, { book: "Ezekiel", chapters: "33" }] },
  { day: 317, readings: [{ book: "Jeremiah", chapters: "51-52" }, { book: "Luke", chapters: "15" }, { book: "Ezekiel", chapters: "34" }] },
  { day: 318, readings: [{ book: "Lamentations", chapters: "1-2" }, { book: "Luke", chapters: "16" }, { book: "Ezekiel", chapters: "35-36" }] },
  { day: 319, readings: [{ book: "Lamentations", chapters: "3-5" }, { book: "Luke", chapters: "17" }, { book: "Ezekiel", chapters: "37" }] },
  { day: 320, readings: [{ book: "Ezekiel", chapters: "1-3" }, { book: "Luke", chapters: "18" }, { book: "Ezekiel", chapters: "38-39" }] },
  { day: 321, readings: [{ book: "Ezekiel", chapters: "4-6" }, { book: "Luke", chapters: "19" }, { book: "Ezekiel", chapters: "40" }] },
  { day: 322, readings: [{ book: "Ezekiel", chapters: "7-9" }, { book: "Luke", chapters: "20" }, { book: "Ezekiel", chapters: "41-42" }] },
  { day: 323, readings: [{ book: "Ezekiel", chapters: "10-12" }, { book: "Luke", chapters: "21" }, { book: "Ezekiel", chapters: "43-44" }] },
  { day: 324, readings: [{ book: "Ezekiel", chapters: "13-15" }, { book: "Luke", chapters: "22" }, { book: "Ezekiel", chapters: "45-46" }] },
  { day: 325, readings: [{ book: "Ezekiel", chapters: "16" }, { book: "Luke", chapters: "23" }, { book: "Ezekiel", chapters: "47-48" }] },
  { day: 326, readings: [{ book: "Ezekiel", chapters: "17-19" }, { book: "Luke", chapters: "24" }, { book: "Daniel", chapters: "1" }] },
  { day: 327, readings: [{ book: "Ezekiel", chapters: "20-21" }, { book: "John", chapters: "1" }, { book: "Daniel", chapters: "2" }] },
  { day: 328, readings: [{ book: "Ezekiel", chapters: "22-23" }, { book: "John", chapters: "2" }, { book: "Daniel", chapters: "3" }] },
  { day: 329, readings: [{ book: "Ezekiel", chapters: "24-26" }, { book: "John", chapters: "3" }, { book: "Daniel", chapters: "4" }] },
  { day: 330, readings: [{ book: "Ezekiel", chapters: "27-28" }, { book: "John", chapters: "4" }, { book: "Daniel", chapters: "5" }] },
  { day: 331, readings: [{ book: "Ezekiel", chapters: "29-31" }, { book: "John", chapters: "5" }, { book: "Daniel", chapters: "6" }] },
  { day: 332, readings: [{ book: "Ezekiel", chapters: "32-33" }, { book: "John", chapters: "6" }, { book: "Daniel", chapters: "7" }] },
  { day: 333, readings: [{ book: "Ezekiel", chapters: "34-35" }, { book: "John", chapters: "7" }, { book: "Daniel", chapters: "8" }] },
  { day: 334, readings: [{ book: "Ezekiel", chapters: "36-37" }, { book: "John", chapters: "8" }, { book: "Daniel", chapters: "9" }] },
  { day: 335, readings: [{ book: "Ezekiel", chapters: "38-39" }, { book: "John", chapters: "9" }, { book: "Daniel", chapters: "10" }] },
  { day: 336, readings: [{ book: "Ezekiel", chapters: "40-41" }, { book: "John", chapters: "10" }, { book: "Daniel", chapters: "11" }] },
  { day: 337, readings: [{ book: "Ezekiel", chapters: "42-43" }, { book: "John", chapters: "11" }, { book: "Daniel", chapters: "12" }] },
  { day: 338, readings: [{ book: "Ezekiel", chapters: "44-45" }, { book: "John", chapters: "12" }, { book: "Hosea", chapters: "1-3" }] },
  { day: 339, readings: [{ book: "Ezekiel", chapters: "46-48" }, { book: "John", chapters: "13" }, { book: "Hosea", chapters: "4-6" }] },
  { day: 340, readings: [{ book: "Daniel", chapters: "1-2" }, { book: "John", chapters: "14" }, { book: "Hosea", chapters: "7-9" }] },
  { day: 341, readings: [{ book: "Daniel", chapters: "3-4" }, { book: "John", chapters: "15" }, { book: "Hosea", chapters: "10-12" }] },
  { day: 342, readings: [{ book: "Daniel", chapters: "5-6" }, { book: "John", chapters: "16" }, { book: "Hosea", chapters: "13-14" }] },
  { day: 343, readings: [{ book: "Daniel", chapters: "7-8" }, { book: "John", chapters: "17" }, { book: "Joel", chapters: "1-3" }] },
  { day: 344, readings: [{ book: "Daniel", chapters: "9-10" }, { book: "John", chapters: "18" }, { book: "Amos", chapters: "1-3" }] },
  { day: 345, readings: [{ book: "Daniel", chapters: "11-12" }, { book: "John", chapters: "19" }, { book: "Amos", chapters: "4-6" }] },
  { day: 346, readings: [{ book: "Hosea", chapters: "1-4" }, { book: "John", chapters: "20" }, { book: "Amos", chapters: "7-9" }] },
  { day: 347, readings: [{ book: "Hosea", chapters: "5-8" }, { book: "John", chapters: "21" }, { book: "Obadiah", chapters: "1" }] },
  { day: 348, readings: [{ book: "Hosea", chapters: "9-11" }, { book: "Acts", chapters: "1" }, { book: "Jonah", chapters: "1-4" }] },
  { day: 349, readings: [{ book: "Hosea", chapters: "12-14" }, { book: "Acts", chapters: "2" }, { book: "Micah", chapters: "1-3" }] },
  { day: 350, readings: [{ book: "Joel", chapters: "1-3" }, { book: "Acts", chapters: "3" }, { book: "Micah", chapters: "4-5" }] },
  { day: 351, readings: [{ book: "Amos", chapters: "1-3" }, { book: "Acts", chapters: "4" }, { book: "Micah", chapters: "6-7" }] },
  { day: 352, readings: [{ book: "Amos", chapters: "4-6" }, { book: "Acts", chapters: "5" }, { book: "Nahum", chapters: "1-3" }] },
  { day: 353, readings: [{ book: "Amos", chapters: "7-9" }, { book: "Acts", chapters: "6" }, { book: "Habakkuk", chapters: "1-3" }] },
  { day: 354, readings: [{ book: "Obadiah", chapters: "1" }, { book: "Acts", chapters: "7" }, { book: "Zephaniah", chapters: "1-3" }] },
  { day: 355, readings: [{ book: "Jonah", chapters: "1-4" }, { book: "Acts", chapters: "8" }, { book: "Haggai", chapters: "1-2" }] },
  { day: 356, readings: [{ book: "Micah", chapters: "1-4" }, { book: "Acts", chapters: "9" }, { book: "Zechariah", chapters: "1-3" }] },
  { day: 357, readings: [{ book: "Micah", chapters: "5-7" }, { book: "Acts", chapters: "10" }, { book: "Zechariah", chapters: "4-6" }] },
  { day: 358, readings: [{ book: "Nahum", chapters: "1-3" }, { book: "Acts", chapters: "11" }, { book: "Zechariah", chapters: "7-9" }] },
  { day: 359, readings: [{ book: "Habakkuk", chapters: "1-3" }, { book: "Acts", chapters: "12" }, { book: "Zechariah", chapters: "10-12" }] },
  { day: 360, readings: [{ book: "Zephaniah", chapters: "1-3" }, { book: "Acts", chapters: "13" }, { book: "Zechariah", chapters: "13-14" }] },
  { day: 361, readings: [{ book: "Haggai", chapters: "1-2" }, { book: "Acts", chapters: "14" }, { book: "Malachi", chapters: "1-2" }] },
  { day: 362, readings: [{ book: "Zechariah", chapters: "1-4" }, { book: "Acts", chapters: "15" }, { book: "Malachi", chapters: "3-4" }] },
  { day: 363, readings: [{ book: "Zechariah", chapters: "5-9" }, { book: "Acts", chapters: "16" }, { book: "Revelation", chapters: "1-2" }] },
  { day: 364, readings: [{ book: "Zechariah", chapters: "10-14" }, { book: "Acts", chapters: "17" }, { book: "Revelation", chapters: "3-5" }] },
  { day: 365, readings: [{ book: "Malachi", chapters: "1-4" }, { book: "Acts", chapters: "18" }, { book: "Revelation", chapters: "6-7" }] },
];

/**
 * Get the reading schedule for a specific plan
 */
export function getReadingSchedule(planId: string): DailyReading[] | null {
  switch (planId) {
    case "bible-in-year":
      return bibleInYearSchedule;
    default:
      return null;
  }
}

/**
 * Get today's reading for a specific plan and day
 */
export function getDailyReading(planId: string, day: number): DailyReading | null {
  const schedule = getReadingSchedule(planId);
  if (!schedule) return null;
  return schedule.find(r => r.day === day) || null;
}

/**
 * Format readings as a readable string
 */
export function formatReadings(readings: DailyReading["readings"]): string {
  return readings.map(r => `${r.book} ${r.chapters}`).join(", ");
}
